--query 2.1
SELECT S.TICKET_TYPE, T.DATEMONTH,
    SUM(S.PRICE) / COUNT(DISTINCT T.DATE),

    SUM(SUM(S.PRICE)) OVER (PARTITION BY T.DATEYEAR),

    100 * SUM(S.N_TICKET) / 
    SUM(SUM(S.N_TICKET)) OVER (PARTITION BY T.DATEMONTH)
FROM SALES S, TIMEDIM T
WHERE S.TVALIDITY_ID = T.TIME_ID
GROUP BY S.TICKET_TYPE, T.DATEYEAR, T.DATEMONTH;

--query 2.2
SELECT M.MUSEUM_ID, S.TICKET_TYPE,
    SUM(S.PRICE) / SUM(S.N_TICKET),

    100 * SUM(S.PRICE) / 
    SUM(SUM(S.PRICE)) OVER (PARTITION BY M.CATEGORY),

    RANK () OVER (ORDER BY SUM(S.N_TICKET) DESC)
FROM SALES S, TIMEDIM T, MUSEUM M
WHERE S.TIME_ID = T.TIME_ID AND T.TIME_ID = 2021 AND S.MUSEUM_ID = M.MUSEUM_ID
GROUP BY M.MUSEUM_ID, S.TICKET_TYPE, M.CATEGORY;