--query 2.1
SELECT S.TICKET_TYPE, T.DATEMONTH,
    SUM(S.PRICE) / COUNT(DISTINCT T.DATE),

    SUM(SUM(S.PRICE)) OVER (PARTITION BY T.DATEYEAR),

    100 * SUM(S.N_TICKET) / COUNT(DISTINCT T.DATE)
FROM SALES S, TIMEDIM T
WHERE S.TVALIDITY_ID = T.TIME_ID
GROUP BY S.TICKET_TYPE, T.DATEYEAR, T.DATEMONTH;