--these are the logs associated to TABLES and ATTRIBUTES that we
--want to update with the FAST option into the mat view
CREATE MATERIALIZED VIEW LOG ON INCOME
WITH SEQUENCE, ROWID
(BranchID, ServiceID, TimeID, #Consultancies, Income)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON SERVICE
WITH SEQUENCE, ROWID
(ServiceID, Type)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON TIME
WITH SEQUENCE, ROWID
(TimeID, Semester)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON CONSULTANTS_BRANCH
WITH SEQUENCE, ROWID
(BranchID, GeographicArea)
INCLUDING NEW VALUES; 