--1)
SELECT T.DATEMONTH, P.PHONERATETYPE,
    SUM(F.PRICE)
FROM FACTS F, TIMEDIM T, PHONERATE P
WHERE F.ID_TIME = T.ID_TIME AND F.ID_PHONERATE = P.ID_PHONERATE 
    AND T.DATEYEAR = 2003
GROUP BY GROUPING SETS (
    (T.DATEMONTH, P.PHONERATETYPE),
    (),
    P.PHONERATETYPE,
    T.DATEMONTH
);

--2)
SELECT T.DATEMONTH,
    SUM(F.NUMBEROFCALLS) AS monthly_calls_amount,
    SUM(F.PRICE) AS monthly_tot_income,
    RANK() OVER (ORDER BY SUM(F.NUMBEROFCALLS) DESC) AS rank_by_amount
FROM FACTS F, TIMEDIM T
WHERE F.ID_TIME = T.ID_TIME
GROUP BY T.DATEMONTH;

--3)
SELECT T.DATEMONTH,
    SUM(F.NUMBEROFCALLS) AS monthly_calls_amount,
    RANK() OVER (ORDER BY SUM(F.NUMBEROFCALLS) DESC) AS rank_by_amount
FROM FACTS F, TIMEDIM T
WHERE F.ID_TIME = T.ID_TIME AND T.DATEYEAR = 2003
GROUP BY T.DATEMONTH;

--4)
SELECT P.PHONERATETYPE,
    SUM(F.PRICE) AS tot_amount_by_phonerate
FROM FACTS F, TIMEDIM T, PHONERATE P
WHERE F.ID_TIME = T.ID_TIME AND T.DATEYEAR = 2003 AND T.DATEMONTH LIKE '%JAN%'
    AND F.ID_PHONERATE = P.ID_PHONERATE
GROUP BY P.PHONERATETYPE;

--5)
SELECT T.DATEYEAR, T.DATEMONTH,
    SUM(F.PRICE) AS tot_monthly_income,
    SUM(SUM(F.PRICE)) OVER (PARTITION BY T.DATEYEAR) AS cumulative_yearly_income
FROM FACTS F, TIMEDIM T
WHERE F.ID_TIME = T.ID_TIME
GROUP BY T.DATEYEAR, T.DATEMONTH;

--6) TODO: CHECK IF CORRECT
SELECT T.DATEMONTH, P.PHONERATETYPE,
    SUM(F.PRICE) AS tot_income,
    SUM(F.PRICE) /
        SUM(SUM(F.PRICE)) OVER (PARTITION BY P.PHONERATETYPE) AS perc_to_all_months,
    SUM(F.PRICE) /
        SUM(SUM(F.PRICE)) OVER (PARTITION BY T.DATEMONTH) AS perc_to_all_pr
FROM FACTS F, TIMEDIM T, PHONERATE P
WHERE F.ID_TIME = T.ID_TIME AND T.DATEYEAR = 2003
GROUP BY GROUPING SETS(
    T.DATEMONTH,
    P.PHONERATETYPE
);